#! /bin/sh

bspc monitor DisplayPort-0 -d 1 2 3 4 5 
bspc monitor HDMI-A-0 -d 6 7 8 9 

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/fab/Immagini/Sfondi/flowers.png
picom --experimental-backends -b
if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
	xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 144 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rate 75 --rotate normal --right-of DisplayPort-0
fi
/home/fab/.config/polybar/launch.sh
xset m 1/1
nm-applet
dunst
#/home/fab/.config/bspwm/borders 
setxkbmap us




#bspc monitor -d I II III IV V 



#startup

bspc config border_width        3 
bspc config active_border_color "#d3c6aa"
bspc config focused_border_color "#d3c6aa"
bspc config normal_border_color "#a7c080"
bspc config window_gap           7


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 7ms

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^6'



